const url = "https://projectcloudbased.vercel.app/convert"

let html = "<!DOCTYPE html>"
html += '<html lang="en">'
html+= "	<head>"
html += "		<meta charset=\"UTF-8\">"
html += "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
html += "		<title>MPOP Reverse II MP3\/Video Downloader</title>"
html += "		<meta name=\"description\" content=\"A platform to download videos from youtube/facebook\">"
html += "		<style>"
html += "			* {"
html += "				margin: 0;"
html += "				padding: 0;"
html += "				box-sizing: border-box;"
html += "				user-select: none;"
html += "				outline: none;"
html += "			}"
html += "			"
html += "			#mpop-layout-yt-downloader{"
html += "				width: 500px;"
html += "				height: 500px;"
html += "				position: fixed;"
html += "				z-index: 100;"
html += "				bottom: 0;"
html += "			}"
html += "			"
html += "			main {"
html += "				display: flex;"
html += "				flex-direction: column;"
html += "				align-items: center;"
html += "				width: 500px;"
html += "				height: 500px;"
html += "				border: 1px; red solid;"
html += "			}"
html += "			"
html += "			main > div {"
html += "				display: flex;"
html += "				flex-direction: column;"
html += "				width: 75%;"
html += "				box-sizing: border-box;"
html += "				-webkit-box-sizing: border-box;"
html += "				-moz-box-sizing: border-box;"
html += "				margin: 1em;"
html += "				box-shadow: 3px 3px 5px #333333;"
html += "				align-items: center;"
html += "				padding: .5em;"
html += "				border-radius: .5em;"
html += "			}"
html += "			"
html += "			main > div > input {"
html += "				border: 0;"
html += "				background-color: transparent;"
html += "				border-radius: .5em;"
html += "				/* box-shadow: 3px 3px 5px #333333; */"
html += "				border: 1px black solid;"
html += "				font-family: 'Times New Roman', Times, serif;"
html += "				padding: .15em .5em;"
html += "				width: 90%;"
html += "				margin: .5em;"
html += "				box-sizing: border-box;"
html += "				-webkit-box-sizing: border-box;"
html += "				-moz-box-sizing: border-box;"
html += "			}"
html += "			"
html += "			main > div > #links {"
html += "				display: flex;"
html += "				flex-direction: column;"
html += "				align-items: center;"
html += "				justify-content: center;"
html += "			}"
html += "			"
html += "			main > div > h3, main > div > h5{"
html += "				text-align: center;"
html += "			}"
html += "			"
html += "			main > div > #links {"
html += "				max-height: 50vh;"
html += "				overflow-y: scroll;"
html += "				width: 100%;"
html += "				margin: 1em;"
html += "				padding: 0 .75em;"
html += "			}"
html += "			"
html += "			main > div > #links > a{"
html += "				width: 100%;"
html += "				text-align: center;"
html += "				color: black;"
html += "				text-decoration: none;"
html += "				background-color: wheat;"
html += "				border-radius: .5em;"
html += "				box-shadow: 3px 3px 5px #333333;"
html += "				margin: .25em;"
html += "				padding: .1em 1em;"
html += "			}"
html += "		</style>"
html += "	</head>"
html += "	<body id=\"mpop-layout-yt-downloader\">"
html += "		<main>"
html += "			<div>"
html += "				<h3 id=\"title\">Audio Video Downloader</h3>"
html += "				<h5 id=\"source\"></h5>"
html += "				<h5 id=\"duration\"></h5>"
html += "				<input type=\"url\" id=\"url\" placeholder=\"Enter url here\">"
html += "				<div id=\"links\"></div>"
html += "			</div>"
html += "		</main>"
html += "	</body>"
html += "</html>"
html += ""

let html1 = document.body.innerHTML
document.body.innerHTML = html + html1